### ISSUE TITLE
addon fix works partially (4.0)

### ISSUE THREAD

**Issue by batonchick1** [romanvolodin/dynamic_parent#12]
Hello. Interestingly, the addon's fix partially doesn't work: it links objects in "object" mode without any problems.
It also connects an armature in pose mode to an object in "object mode" if the armature is the parent, but if the parent is an object in "object mode" or if you need to connect two different armatures in pose mode, it throws an error:

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dynamic_parent.py", line 287, in execute
    dp_create_dynamic_parent_pbone(self)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\dynamic_parent.py", line 188, in dp_create_dynamic_parent_pbone
    bpy.ops.constraint.childof_set_inverse(
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 106, in __call__
    C_exec, C_undo = _BPyOpsSubModOp._parse_args(args)
  File "C:\Program Files\Blender Foundation\Blender 4.0\4.0\scripts\modules\bpy\ops.py", line 60, in _parse_args
    raise ValueError("1-2 args execution context is supported")
ValueError: 1-2 args execution context is supported

**Comment by romanvolodin** [comment]
Thanks for report! Will take a look tomorrow.

пн, 4 дек. 2023 г., 21:57 batonchick1 ***@***.***>:

**Comment by romanvolodin** [comment]
Looks like fixed in d4e6188. At least it works fine in my simple scene.

**Comment by PurrfectDreamm** [comment]
> Looks like fixed in [d4e6188](https://github.com/romanvolodin/dynamic_parent/commit/d4e61884124caace232b49e80948c23b7909fa3b). At least it works fine in my simple scene.

Yes, it's fixed! Thank you very much! Большое спасибо, теперь всё идеально работает, этот аддон невероятно полезен для меня и я благодарен тебе за твою работу.
