### ISSUE TITLE
Error when parenting an armature to another armature's bone

### ISSUE THREAD

**Issue by HeCorr** [romanvolodin/dynamic_parent#4]
I'm trying to parent an armature to another armature's bone and it's throwing an error:

```
Python: Traceback (most recent call last):
  File "C:\Users\Henrique\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dynamic_parent.py", line 251, in execute
    const = get_last_dymanic_parent_constraint(obj)
  File "C:\Users\Henrique\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\dynamic_parent.py", line 58, in get_last_dymanic_parent_constraint
    if not obj.constraints:
AttributeError: 'NoneType' object has no attribute 'constraints'

location: <unknown location>:-1
```

Blender version: `3.0.1` build `dc2d18018171`
Dynamic Parent version: `1.0.0`

Here's a video demonstrating the issue:

https://user-images.githubusercontent.com/75134774/153648413-2fa1a88d-cf29-4919-b37f-76ebedc3733e.mp4

The current workaround is to parent the child armature to an empty directly and dynamically parent the empty to the main armature:

https://user-images.githubusercontent.com/75134774/153648686-a5cd3c15-51b2-4620-b2e2-ff42c859ed75.mp4

...which is not the end of the world but I would rather not have to do that, specially when working with many child armatures.

**Comment by romanvolodin** [comment]
You have to select both armatures and switch into Pose Mode. Then DynamicParent will work.

**Comment by HeCorr** [comment]
But that requires me to have a root bone in the child armature, which in my case I don't.

It's possible to manually add a ChildOf constraint to the armature, so shouldn't it just work? Is there a limitation in Blender's API?

**Comment by romanvolodin** [comment]
You don't need any root bone. It should work as it is.

https://user-images.githubusercontent.com/9511905/153729788-15f69e28-d774-41e4-b8ad-5d105f2dc9dc.mp4

**Comment by HeCorr** [comment]
What I meant by a root bone is a bone that all other bones are parented to.

The way you showed in the video I still need to parent a **_specific bone_**, not the **_armature object_**, which is what I want.

In my case I have two disconnected bones and I would have to parent both if I were to use your method (or modify the armature, creating a root bone whose other bones are statically parented to).

I still consider this a limitation and would like to see it implemented in the future if possible, otherwise you can close the issue.
